// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_4HM9LRf1XigDmL4WD3l-M9LqGxfrxo',
    appId: '1:446222208776:web:13ad7f14d393b23d0ea6bd',
    messagingSenderId: '446222208776',
    projectId: 'e-commerce-getx-eafb2',
    authDomain: 'e-commerce-getx-eafb2.firebaseapp.com',
    storageBucket: 'e-commerce-getx-eafb2.firebasestorage.app',
    measurementId: 'G-QMDVC0LS93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADfOo5ATZs6FlGdrUG5uxHkDcv3_MTGws',
    appId: '1:446222208776:android:588eecb0a6f48a6d0ea6bd',
    messagingSenderId: '446222208776',
    projectId: 'e-commerce-getx-eafb2',
    storageBucket: 'e-commerce-getx-eafb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvNdwMJP6hShFG_I7UTtoKATxAk8zn-s',
    appId: '1:446222208776:ios:b1c5e4fc68286ab80ea6bd',
    messagingSenderId: '446222208776',
    projectId: 'e-commerce-getx-eafb2',
    storageBucket: 'e-commerce-getx-eafb2.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvNdwMJP6hShFG_I7UTtoKATxAk8zn-s',
    appId: '1:446222208776:ios:b1c5e4fc68286ab80ea6bd',
    messagingSenderId: '446222208776',
    projectId: 'e-commerce-getx-eafb2',
    storageBucket: 'e-commerce-getx-eafb2.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2_4HM9LRf1XigDmL4WD3l-M9LqGxfrxo',
    appId: '1:446222208776:web:06a96a4fa55af4aa0ea6bd',
    messagingSenderId: '446222208776',
    projectId: 'e-commerce-getx-eafb2',
    authDomain: 'e-commerce-getx-eafb2.firebaseapp.com',
    storageBucket: 'e-commerce-getx-eafb2.firebasestorage.app',
    measurementId: 'G-H2EFG17ERK',
  );
}
